project:
  type: book
  output-dir: docs

book:
  title: "Geographic Data Science for Applied Economists"
  author: "Dr. Carmen Cabrera-Arnau"
  date: today
  chapters:
    - index.qmd
    - part: "Introduction"
      chapters:
        - quarto-notebooks/overview.qmd
        - quarto-notebooks/environPy.qmd
        - quarto-notebooks/download.qmd
    - part: "Contents"
      chapters:
        - quarto-notebooks/spatial-data.qmd
        - quarto-notebooks/geovisualisation.qmd
        - quarto-notebooks/spatial-feature-i.qmd
        - quarto-notebooks/spatial-feature-ii.qmd
        - quarto-notebooks/openstreetmap.qmd
        - quarto-notebooks/transport-costs.qmd
        # - web-mapping.qmd
    - part: "Epilogue"
      chapters:
        - quarto-notebooks/datasets.qmd
        - quarto-notebooks/references.qmd

  page-footer:
    left: |
      Geographic Data Science for Applied Economists by Carmen Cabrera-Arnau.
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  site-url:  https://crmnca.github.io/gds4eco/
  repo-url: https://github.com/CrmnCA/gds4eco
  repo-actions: [edit]
  sharing: [twitter, facebook]
  cover-image: cover-image.jpeg
  cover-image-alt: |
    Alternative text describing the book cover
 

bibliography: references.bib

format:
  html:
    theme: 
    - cosmo
    - r4gds.scss
  pdf:
    documentclass: scrreprt

editor: visual

