# Overview {.unnumbered}

This course provides an introduction to Geographic Data Science for applied economists using Python. It has been designed to be delivered in 9 hours of teaching, split into six sessions of 1.5 hours each.

## Aims

The course has three primary aims:

-   Equip students with essential skills in Geographic Data Science (GDS), improving their statistical and numerical understanding and familiarity with fundamental programming concepts and modern computational tools for GDS;

-   Offer a thorough overview of key methodologies used by Geographic Data Scientists, along with insights on how and when to apply them;

-   Emphasise practical applications of these techniques within real-world geographical and applied settings.

## Learning Outcomes

By the end of this course, students will be able to:

-   Illustrate advanced techniques in GIS/GDS and use them programmatically for importing, manipulating, and analysing data in various formats.

-   Explain the rationale and mechanics behind key methodological approaches in GDS, both from analytical and visual perspectives.

-   Assess the suitability of specific techniques, their capabilities, and how they can address relevant questions.

-   Implement various spatial analysis methods and interpret the outcomes, transforming raw data into meaningful insights.

-   Independently handle new datasets using GIS/GDS tools in a programmatic manner.

-   Demonstrate a sound understanding of how real-world (geo)data are produced, their potential insights and biases, as well as opportunities and limitations.
